LibertyDSNP/sdk-ts

README.md, package-lock.json, package.json
Problem
=======
The version of web3 we were using, plus what we had in package-lock.json was using a version of underscore that had a severe vulnerability.   
Also there is a severe vulnerability in lodash.
[link to Pivotal Tracker #178101352](https://www.pivotaltracker.com/story/show/178101352)
Solution
========
1. Installed latest versions of underscore and lodash explicitly
1. Completely regenerate package-lock.json
1. Run npm audit fix
This leaves us only with this ["low" web3 vulnerability](https://www.npmjs.com/advisories/877) 
1. `npm i`
2. `npm audit` if this does not show you the remaining vulnerability. Only the 1 should be there.
=> fix underscore vuln

.github/workflows/main.yml
When squash-merging just a single commit, it is different than multiple commits. Thanks GitHub.
=> ls-remote does not always get all the commits

src/core/contracts/registry.test.ts, src/core/contracts/registry.ts, src/core/messages/messages.ts, src/test/sdkTestConfig.ts, src/test/testAccounts.ts
Problem
=======
>As the App API, I need to know if a public key has a given permission on a given contract So that I can test a generic signature against a DSNP Id
[Pivotal Tracker #178267391](https://www.pivotaltracker.com/story/show/178267391)
Solution
========
* new plumbing function contracts/registry.ts#validateMessage
* tests for same
* added some test helpers in testAccounts.ts which let you set up a new signer and easily create a new DSNP identity with a new handle all in one go, using the specified test account by its index.
1. tests should all pass
=> Validate messages, signature + permission #178267391

.github/workflows/publish-next.yml, .github/workflows/release.yml
Problem
=======
For some reason the npm v7 upgrade would not work with the matrix strategy (`npm i -g npm`) and failed.
Solution
========
Switched over to the form used by the `@next` release setup
=> Fix CI for Releases

src/config.test.ts, src/config.ts, src/content.test.ts, src/content.ts, src/core/contracts/announcement.ts, src/core/contracts/identity.test.ts, src/core/contracts/identity.ts, src/core/contracts/registry.ts, src/core/messages/messages.ts, src/core/store/interface.test.ts, src/core/store/interface.ts, src/core/utilities/errors.ts, src/handles.test.ts, src/network.test.ts, src/network.ts, src/test/testAccounts.ts
Problem
=======
Add getter methods to config module [link to Pivotal Tracker #178458945](https://www.pivotaltracker.com/story/show/178458945)
Solution
========
Proposed solution:
1. A bunch of `requireFoo` functions which pretty much replace all getters that are being used.  They always throw if Foo is undefined.
1. A requireGetConfig function to use if you want to guarantee multiple things are there.  Pass a list of strings (feels yucky, alternatives requested) and your configOpts.
1. Tests for above
I did not completely do a refactor because I wanted input before I did the rest.
=> getters & refactors

src/config.test.ts, src/config.ts, src/core/contracts/announcement.ts, src/core/contracts/identity.ts, src/core/contracts/registry.ts
Problem
=======
Follow up to #61 , after discussions and looking at the comments
[Finishes #178458945](https://www.pivotaltracker.com/story/show/178458945)
Solution
========
* requireGetConfig is gone.
* Use single getters if you want a guarantee that something is defined or will throw.
* Keeping 'requireGetFoo' and 'getFoo' where applicable as it's an indicator of what is returned; Configs that are not optional fields don't need a 'require' and getters for optional settings if you don't care if they aren't set can be implemented as needed.
* add @returns in typedocs
* tests for all the getters
This eliminates the code smell of using the "as Provider" and friends.
Code is even simpler than before.
1. Tests pass.
=> get rid of requireGetConfig, use single getters

src/handles.test.ts, src/handles.ts, src/network.test.ts, src/network.ts
Problem
=======
We don't want to use handles in any methods exposed to the user except `resolveHandle()`.
[#178559050](https://www.pivotaltracker.com/story/show/178559050)
Solution
========
Replace handles with DSNPUserIds in all methods using them and delete `authenticateHandle()`
=> Removed autheticateHandle method and updated follow and unfollow methods

src/config.test.ts, src/config.ts, src/content.test.ts, src/network.test.ts
Problem
=======
We would prefer if the `setConfig()` method merged new config options with existing ones to avoid losing settings when called.
[#178559063](https://www.pivotaltracker.com/story/show/178559063)
Solution
========
Update it to do that
=> Changed setConfig to preserve existing keys in the config when called

src/content.ts, src/core/batch/batchMesssages.ts, src/core/messages/messages.ts, src/network.ts
Problem
=======
We had a type coercion which could lead to issues
Solution
========
Removed the coercion through building a generic type that used `& { key: value }` instead.
* Replaced BatchDSNPMessage with a better generic that works the same way.
=> Fix BatchDSNPMessage types to not need coercion

package-lock.json, package.json
Problem
=======
[Related to Pivotal Tracker #178456668](https://www.pivotaltracker.com/story/show/178456668), Now that parquetjs has a 1.1.0 release, point the SDK at it.
Solution
========
Update package*.json
1.  CI should pass
1.  The SDK should be useable by other repos now that LZO support is gone completely.
Not included:
---
To get a browser version of the SDK we'll need to add a browser target similar to what we did for [parquetjs v1.1.1](https://github.com/LibertyDSNP/parquetjs/pull/17)
=> Use parquetjs v1.1.0

.github/workflows/main.yml
Swap Ganache for Hardhat. Version 6 of
Ganache has the chainid opcode hardcoded to 1. 
As a result, it prevents EIP-712 signatures from being valid.
The EIP-712 domain separator includes a chain-id that
will cause a discrepancy when signing and verifying
on-chain.
=> chore(CI): swap Ganache for Harhat

src/generators/activityPubGenerators.test.ts, src/generators/activityPubGenerators.ts
Problem
=======
Our activity pub generators do not include `published` timestamps, meaning they do not comply with our own spec.
[#178604714](https://www.pivotaltracker.com/story/show/178604714)
Solution
========
Update them to use the `activityPub.create` method which automatically sets `published`.
=> Changed activity pub generators to use activity pub create method

package-lock.json, package.json, src/core/batch/batch.ts, src/core/store/interface.ts
Problem
=======
There are a few issues that prevent generating parquetjs batch files correctly when running in the browser (probably on the server as well).
1. We wrap the incoming writeStream and overwrite its `write` method to hash outgoing data. We do not do this for the `end` method, so end doesn't get called on the underlying writeStream.
2. Our `WriteStream` interface has a 2 argument and 3 argument signature for `end`, but parquetjs is calling a 1 argument version (which exists on Nodejs's `Writable` interface).
3. We are not waiting for `appendRow` to complete.
4. We are specifying a version of parquetjs that does not support CommonJS or ESM builds in the browser.
Solution
========
This PR address all 4 issues
=> fix issues creating batch files in the browser

CHANGELOG.md, README.md, src/content.test.ts, src/content.ts, src/core/store/interface.ts, src/test/testStore.ts
No story for this, just something we've been needing to do that I knocked out in my spare time.
Problem
=======
We didn't know how we'd use the store adapter when we first wrote the interface for it, and now we have redundant put methods, `put()` and `putStream()`, where only one is really needed.
Solution
=======
Remove `put()` from the store interface
=> Removed put from store interface

CHANGELOG.md, src/core/contracts/identity.test.ts, src/core/contracts/identity.ts, src/core/contracts/subscription.ts
Add ability to retrieve logs for adding and
removing delegates:
- DSNPRemoveDelegate
- DSNPAddDelegate
This allows client to be able to resolve active
and inactive delegates.
=> feat(identity): add ability to retrieve logs

CHANGELOG.md, src/core/announcements/factories.ts, src/core/announcements/validation.ts, src/core/batch/parquetSchema.test.ts, src/core/batch/parquetSchema.ts, src/core/utilities/time.ts
Problem
=======
Add created_at field to GraphChange type.
[Fixes #178607496](https://www.pivotaltracker.com/story/show/178607496)
Double Checks:
* Add createdAt field to GraphChange announcement interface
* Add the type check to the GraphChange validator
1. CI should pass.
=> Add created_at field to GraphChange type

CHANGELOG.md, src/core/contracts/subscription.test.ts, src/core/contracts/subscription.ts
Problem
=======
In `subscribeToBatchPublications`, we needed to check the length of pastLogs before trying to look at the blockNumber of one of its elements.
[Fixes #179033826](https://www.pivotaltracker.com/story/show/179033826)
Solution
========
Do the length check
Add a regression test that shows the red/green behavior
Double Checks:
1. The test passes
1. For extra credit you can build sdk and make example-client use it, then launch a hardhat localnet with no logs or anything, and login to the example client.  You should not see the error message as shown in the Tracker story.
=> check for pastLogs.length before continuing in subscribeToBatchPublications

README.md
Problem
=======
We need to list where our tesnet nodes live and what the addresses are for the deployed contracts so that people can access them. 
Solution
========
Update README to show addresses of both testnet nodes and contracts
=> update readme with contract addresses

CHANGELOG.md, src/core/contracts/registry.ts
Problem
=======
OpenEthereum can be configured to not return the revert error message which tripped up the resolveRegistration code testing for it.
Solution
========
Removed the check for the error message
with @amparks100 
Double Checks:
* Updated registry.resolveRegistration to support not found cases for nodes that do not return a failure reason.
=> Not all ethereum nodes will return a message with why something reverted

CHANGELOG.md, src/content.ts
Now not using destructuring because of, what I can only assume, is
"this" style issues. Basically a private member _writableState will be
undefined. Using the object directly fixes that issue
Problem
=======
using destructuring causes FileStreams to have undefined members.
[Pivotal issue](https://www.pivotaltracker.com/story/show/179110784)
Solution
========
No longer use destructuring and call the WriteStream methods .write and .end directly
Double Checks:
- [] Did you update the changelog?
No longer using destructuring when working with the WriteStream in the putStream callback flow
A bit tough as I needed to consume the library in another app to make sure it worked.
=> No longer using destructuring

CHANGELOG.md, src/core/activityContent/validation.test.ts, src/core/activityContent/validation.ts
Problem
=======
Published regex did not support fractional seconds or other timezone offset options
[#179076218](https://www.pivotaltracker.com/story/show/179076218)
Solution
========
Updated the regex
Double Checks:
=> Update the published datetime regex

CHANGELOG.md, src/handles.test.ts, src/handles.ts
Problem
=======
sdk.createRegistration said it was returning a DSNPUserURI, but it was not.
Solution
========
Made it return a DSNPUserURI
Double Checks:
=> sdk.createRegistration correctly returns a DSNPUserURI

CHANGELOG.md, src/core/contracts/publisher.test.ts, src/core/contracts/publisher.ts, src/core/contracts/subscription.ts
Problem
=======
The announcements API has a single method to get the contract for batch and subscribe operations. This method requires a signer to connect. This is necessary for the batch operation. The subscription (specifically the dsnpBatchFilter) is read only, so should be capable of running with just a provider.
[#178901784](https://www.pivotaltracker.com/story/show/178901784)
Solution
========
Used the interface instead of the contract to get the needed topic data.
Double Checks:
* Switched dsnpBatchFilter to use the interface instead of the contract to create the filter.
=> dsnpBatchFilter does not require any provider or signer

CHANGELOG.md, src/core/index.ts, src/test/importTest/index.ts
Problem
=======
sdk.core.identifiers were not exported, but they should be for people to use them
Solution
========
Added it to the exports
Double Checks:
=> Export core identifiers

CHANGELOG.md, package-lock.json, package.json
Problem
=======
Ethers js was out of date
Solution
========
Updated ethers to 5.4.4
Double Checks:
* Update Ethersjs 5.3.0 -> 5.4.4
* Update ts-node 10.1.0 -> 10.2.0
=> Update Ethers to 5.4.4

src/core/contracts/subscription.test.ts, src/core/contracts/subscription.ts, src/core/contracts/utilities.ts, src/core/contracts/utilitites.test.ts
Extract code that gets past logs and
subscribes to new log events into
\#subscribeToEvent function.
This allows the ability subscribe
and fetch past logs to used for
other event subscriptions.
=> refactor(batch-subscription): extract common code

CHANGELOG.md, package-lock.json, package.json
- Ability to filter registry update events based on start and end block
- Exported sdk.core.identifiers
- Ability to subscribe to DSNPRegistryUpdate events
- Renamed BatchPublicationCallbackArgs -> BatchPublicationLogData
- Updated subscribeToBatchPublications to not need a signer
- sdk.core.contracts.publisher.dsnpBatchFilter is no longer async
- Updated Ethers from 5.3.0 -> 5.4.4
=> release v2.0.2

CHANGELOG.md, src/core/contracts/publisher.test.ts, src/core/contracts/publisher.ts
Problem
=======
`dsnpBatchFilter()` in `sdk/core/contracts/publisher` fails to output the correct result for `AnnouncementType.Tombstone` due to JavaScript type coercion nonsense
[#178901784](https://www.pivotaltracker.com/story/show/178901784)
Solution
========
Changed `dsnpBatchFilter()` to work properly for `AnnouncementType.Tombstone`.
* Changed condition in `dsnpBatchFilter()` to check undefined instead of falsey-ness
* Added test to prevent bug in future
=> Fixed bug in sdk/core/contracts/publisher#dsnpBatchFilter()

CHANGELOG.md, src/core/contracts/identity.ts, src/core/contracts/registry.ts
Problem
=======
There was a bug whereby if we passed in the regular Ethereum address, fetching registrations would fail because it's expecting the checksummed version. 
Kind of [part of #178933068](https://www.pivotaltracker.com/story/show/178933068)
Solution
========
Call ethers.utils.getAddress to ensure we use checksum address version in `getRegistrationsByWalletAddress` to ensure we provide the correct version of the address.
with @wilwade , @acruikshank 
Double Checks:
* Ensure we fetch registrations using Ethereum checksum address in getRegistrationsByWalletAddress
* Update changelog
Tests should all pass.
If you run a local hardhat node and deploy contracts, the following test code output the …
=> Ensure we fetch registrations using Ethereum checksum address

CHANGELOG.md, src/content.ts, src/core/activityContent/errors.ts, src/core/activityContent/factories.ts, src/core/activityContent/validation.test.ts, src/core/activityContent/validation.ts
Problem
=======
We need more informative errors.
[Fixes #179106793](https://www.pivotaltracker.com/story/show/179106793)
Solution
========
Since the only entry points to the validations threw an error if the ActivityContent(Note|Profile) was invalid, almost everything now throws an error if it doesn't validate, however, sometimes we only need one item of a list to be valid, in particular, attachments.  Attachment validation has been abstracted.
1. Anything that throws an error when something is not valid has been renamed to `requireFoo`
1. Functions that do simple type checking without validating contents should end with `Type`
1. If an attachment has multiple URLs, only one need be valid.  The following examples would be valid:
1. One url has only unsupported hash algorithms - MD5 + …
=> Bugs/better errors #179106793

src/core/activityContent/factories.ts
Update JSDocs for factories such as createNote to
clarify that the options field can only override
default values and not be used to set custom data.
=> chore(factories): update JSdocs

CHANGELOG.md, src/core/batch/parquetSchema.test.ts, src/core/batch/parquetSchema.ts
Problem
=======
The objectId (i.e. the followee or unfollowee) of a graph change announcement is missing from the output when reading from a parquet batch created with the SDK. It turns out this field is never written to the file.
Solution
========
Add `objectId` to the parquet schema for graph change announcements.
Double Checks:
* Add `objectId` to `GraphChangeSchema`
* Also add `objectId` to `GraphChangeSchema` test.
1. Write a GraphChange annoucement to a batch file.
1. Either inspect the file directly or read its contents.
1. Note that it contains data for the `objectId`.
=> add objectid to graphchange parquet schema

CHANGELOG.md, src/core/contracts/identity.test.ts, src/core/contracts/identity.ts, src/core/contracts/registry.ts, src/core/contracts/subscription.test.ts, src/core/contracts/subscription.ts, src/core/contracts/utilities.ts
Problem
=======
We are missing `transactionIndex` and `logIndex` data from subscriptions and registry updates. [link to Pivotal Tracker #179304614](https://www.pivotaltracker.com/story/show/179304614)
Solution
========
Add the data back. 
Double Checks:
- [✅ ] Did you update the changelog?
- [✅ ] Any new modules need to be exported?
- [✅ ] Are new methods in the right module?
- [✅ ] Are new methods/modules in core or not (i.e. porcelain or plumbing)?
- [✅ ] Do you have good documentation on exported methods?
* added `transactionIndex` and `logIndex` fields to subscription and registry updated.
Note: This is currently blocking the indexer team. So this PR is against a patch branch that does not include the latest breaking changes. We will …
=> add logIndex and transactionIndex to subscription data

CHANGELOG.md, src/core/announcements/crypto.ts, src/core/announcements/factories.ts, src/core/announcements/services.ts, src/core/announcements/validation.test.ts, src/core/batch/batch.ts, src/core/batch/parquetSchema.ts, src/core/utilities/time.ts, src/core/utilities/validation.ts, src/createPublication.ts, src/generators/batchFileGenerators.ts
Problem
=======
While working on updating the SDK to match spec v0.10.0, I found some type issues that could be resolved by
- Change AnnouncementWithSignature to take an AnnouncementType instead of a TypedAnnouncement
- use bigint for types instead of BigInt
Solution
========
- Change AnnouncementWithSignature to take an AnnouncementType instead of a TypedAnnouncement
- use bigint for types instead of BigInt
NOTE: No exported types
Double Checks:
=> Better Typed Announcements

CHANGELOG.md, src/core/activityContent/factories.ts, src/core/activityContent/validation.test.ts, src/core/activityContent/validation.ts
Problem
=======
Mentions were requiring a DSNP User Id instead of a URI as is specified
[link to Pivotal Tracker #179340132](https://www.pivotaltracker.com/story/show/179340132)
Solution
========
Required a DSNP User URI for the validator and the factory
Double Checks:
=> Mentions require a a DSNP User URI instead of an Id

CHANGELOG.md, src/core/announcements/factories.ts, src/core/announcements/validation.test.ts, src/core/contracts/registry.test.ts, src/core/contracts/registry.ts, src/core/contracts/subscription.ts, src/core/identifiers/identifiers.test.ts, src/core/identifiers/identifiers.ts, src/handles.test.ts, src/handles.ts, src/network.test.ts, src/test/testAccounts.ts
Problem
=======
We don't want to have ethers BigNumber used outside of the sdk, so better methods to cast these to the correct formats.
Also prep for switching DSNP User Id to bigint
Solution
========
Replaced convert in and out of BigNumber methods with just convertToDSNPUserURI and convertToDSNPUserId
Double Checks:
- Removed convertDSNPUserURIToDSNPUserId
- Removed convertBigNumberToDSNPUserId
- Removed convertDSNPUserIdOrURIToBigNumber
- Removed convertBigNumberToDSNPUserURI
- Added convertToDSNPUserURI
- Added convertToDSNPUserId
=> convertToDSNPUserURI and convertToDSNPUserId replacing BigNumber methods

CHANGELOG.md, src/core/batch/batch.ts
Problem
=======
Had async, but shouldn't have
Solution
========
removed asnyc
Double Checks:
=> Remove extra asyncs

CHANGELOG.md, src/core/contracts/utilities.test.ts, src/core/contracts/utilities.ts
Ensure that when setting fromBlock to zero
that is does not get interpreted as falsy
and that it fetches event data from zero block.
=> fix(subscribeToEvent): allow fromBlock zero value

CHANGELOG.md, src/core/contracts/registry.test.ts, src/core/contracts/utilities.test.ts, src/core/contracts/utilities.ts
Problem
=======
We thought there was a way to be a race condition with starting to get new posts, and getting older posts in subscribeToEvent, but turns out there is not.
[#179437626](https://www.pivotaltracker.com/story/show/179437626)
Solution
========
- Added more documentation to be clear about how ethers works to prevent any overlap.
- Added an extra test around subscribeToEvent
- Updated registry tests to remove test flakiness
with @acruikshank 
Double Checks:
Summary:
- Code documentation and additional test on subscribeToEvent
- Fixed flaky tests around registry
=> Document contracts.utilities.subscribeToEvent

CHANGELOG.md, src/core/config/config.test.ts, src/core/config/config.ts, src/core/contracts/contract.test.ts, src/core/contracts/contract.ts, src/core/contracts/identity.test.ts, src/core/contracts/identity.ts, src/core/contracts/registry.ts, src/core/contracts/subscription.ts, src/core/contracts/utilities.test.ts, src/core/contracts/utilities.ts, src/test/customMatchers.ts, src/types/jest.d.ts
Problem
=======
As a user of the SDK on a long running network, I don't want to search through millions of blocks I don't care about to get the data. I also don't want to have to manually set the default everywhere I call. I just want a config variable to do that work for me.
[PT #179564954](https://www.pivotaltracker.com/story/show/179564954)
Solution
========
Added an optional config param `dsnpStartBlockNumber` that will get used as the default as genesis instead of the chain genesis.
Double Checks:
* Add optional config for `dsnpStartBlockNumber`
* Update methods to use the new `dsnpStartBlockNumber`
* Update `transactionRejectsWith` type which was broken for some IDEs
Also added an example and suggested values in …
=> Config DSNP start block

CHANGELOG.md, src/core/contracts/identity.test.ts, src/core/contracts/registry.test.ts, src/core/contracts/registry.ts, src/core/contracts/subscription.ts, src/core/contracts/utilities.test.ts, src/core/contracts/utilities.ts
Problem
=======
While #171 got most of the places, I missed one. `getDSNPRegistryUpdateEvents` was still defaulting to origin instead of dsnp-start block.
[#12345678](https://www.pivotaltracker.com/story/show/179564954)
Solution
========
Make getDSNPRegistryUpdateEvents default to dsnp-start-block
Double Checks:
* Update docs to be more clear about what the default is for different methods
* getFromBlockDefault supports opts and defaulting to dsnp-start-block
* Default getDSNPRegistryUpdateEvents to dsnp-start-block
=> Feature/default config start block (Part 2)

CHANGELOG.md, src/core/activityContent/factories.ts, src/core/activityContent/validation.test.ts, src/core/activityContent/validation.ts
Problem
=======
[Github issue #126 within spec](https://github.com/LibertyDSNP/spec/issues/126)
The sdk should reflect the changes made to the spec
- Changed accepted type within activitycontent/validation of audio/mp3 -> audip/mpeg
- Removed accepted type of image/jpg
=> changed acceptable types in activity content, validation file
