.github/workflows/main.yml, DOCS.md, README.md, package-lock.json, package.json, scripts/multimodules.js, src/contracts/announcement.ts, src/contracts/contract.test.ts, src/contracts/index.ts, src/index.ts, src/utilities/index.ts
Problem
=======
Moving packages to a better named organization
Solution
========
Update @unfinishedlabs -> @dsnp
=> Update package org from unfinishedlabs -> dsnp

.github/workflows/main.yml, .github/workflows/publish-next.yml, .github/workflows/release.yml
Problem
=======
Needs NPM v7 to properly parse the package-lock files
Solution
========
Add line to update to npm v7 (can be removed once we move to node 16 for the install)
=> Update to use NPM v7

src/batch/parquet-schema.ts
Problem
=======
To write batch files we will need Parquet schema for every DSNP Announcement type.
[Finishes #177940101](https://www.pivotaltracker.com/story/show/177940101)
TODO: review the schema and make sure they are up to date with the message fields.
Solution
========
Add the schema files
with @pairperson1
=> add parquet-schema

README.md, package-lock.json, package.json, src/contracts/announcement.test.ts, src/contracts/announcement.ts, src/contracts/contract.test.ts
Update batch method to match solidity contract interface.
=> feat(batch): update batch method

package-lock.json, package.json
Problem
=======
We had to move another dependency out of devDeps [Really fixes #178206018](https://www.pivotaltracker.com/story/show/178206018) this time for sure
with @wilwade
=> Package install failing because we weren't installing @typechain/web3-v1

README.md
Problem
=======
Clarify instructions on how to run sdk tests
[link to Pivotal Tracker #178201290](https://www.pivotaltracker.com/story/show/178201290)
Solution
========
Update README with instructions on how to run sdk tests
=> clarify instructions for running tests in the SDK

package-lock.json, package.json, src/config/config.ts, src/contracts/index.ts, src/contracts/registry.test.ts, src/contracts/registry.ts, src/test/hardhatRPC.test.ts
Problem
=======
Part 1
Starting the registry contract module
[link to Pivotal Tracker #178266613](https://www.pivotaltracker.com/story/show/178266613)
Solution
========
Built out the registry contract module
* Updated to Ethers 5.3.0
* Added a way to use the config to set the registry contract address
* contracts.registry.register
* contracts.registry.resolveHandleToId
=> Feature/handle availability Part 1

README.md, package-lock.json, package.json, src/config/config.ts, src/storage/s3Node.test.ts, src/storage/s3Node.ts, src/storage/storage.test.ts, src/storage/storage.ts, src/utilities/errors.ts
Problem
=======
Add S3 support for uploading files to Amazon S3.
This allows clients to store batch files and messages.
=> feat(storage): add S3 support

package-lock.json, package.json
Update S3 client as a peer dependency.
=> chore(storage): update s3 dependency

package-lock.json, package.json
[#178432219](https://www.pivotaltracker.com/story/show/178432219)
=> Changed contracts from devDependency to dependency

package-lock.json, package.json, src/contracts/contract.ts, src/contracts/identity.test.ts, src/contracts/identity.ts, src/social/handles.test.ts, src/social/handles.ts
Problem
=======
We need a way to create a user by creating a beacon proxy contract and registering it to a handle.
[link to Pivotal Tracker #178267684](https://www.pivotaltracker.com/story/show/178267684)
Solution
========
This PR adds a method to call to `createAndRegisterBeaconProxy` on the `BeaconFactory` contract, and a porcelain method that calls this function and waits for the result to land on chain.
1. upgrade to latest contracts
2. add contract logic to parse logs
3. add plumbing method to call createAndRegisterBeaconProxy
4. add plumbing method to call the above, wait for the transaction to land, and return the Id.
=> add methods to create and register identity

.gitignore, DOCS.md, README.md, package-lock.json, package.json, src/config.ts, src/index.ts, src/test/sdkTestConfig.ts
Problem
=======
Various Bugs found in QA testing
* Added request to the dependency list
* Fixed to test for separated provider and signer (and fixed code that was broken by that)
=> Pre release QA

package-lock.json, package.json, src/core/batch/batch.test.ts, src/core/batch/batch.ts, src/core/batch/parquetSchema.test.ts, src/core/batch/parquetSchema.ts, src/core/store/interface.test.ts, src/core/store/interface.ts, src/core/store/s3Node.test.ts, src/core/store/s3Node.ts, src/core/utilities/errors.ts, src/test/testStore.ts
Add the ability to write a batch file to storage using streaming.
Writing the batch includes writing the corresponding bloom filter
for every DSNP message type.
=> feat(batch): add ability to write batch

package-lock.json, package.json, src/core/batch/batch.ts
Update #openURL function so that it matches
new interface from ParquetJS API.
=> chore(batch): update reading batch function

.eslintrc, package-lock.json, package.json, src/config.ts, src/content.ts, src/core/activityPub/activityPub.ts, src/core/batch/batch.ts, src/core/contracts/announcement.ts, src/core/contracts/contract.ts, src/core/contracts/identity.ts, src/core/contracts/registry.ts, src/core/contracts/subscription.ts, src/core/messages/messages.ts, src/core/queue/memoryQueue.ts, src/core/queue/queue.ts, src/core/utilities/identifiers.ts, src/core/utilities/json.ts, src/generators/activityPubGenerators.ts, src/generators/batchFileGenerators.ts, src/generators/dsnpGenerators.ts, src/handles.ts, src/network.ts, src/search.ts, src/test/testAccounts.ts
Problem
=======
Missing Docs and inconsistent formatting
Solution
========
Added missing documentation
Double Checks:
* Add jsdoc eslinter and configure it
* Fix lint issues
=> Documentation Linting

src/core/contracts/identity.test.ts, src/core/contracts/identity.ts
Add ability to add or update a delegate.
=> feat(identity): add non-EIP712 delegate method

.eslintrc, package-lock.json, src/core/contracts/identity.test.ts, src/core/contracts/identity.ts, src/core/contracts/utilities.ts, src/test/helpers/EIP712.ts
Add or change permissions for delegate by EIP-712 signature.
=> feat(identity): add delegation methods

src/handles.ts
Remove update registration method in favor of using core methods 
to update handle and identity address core methods.
=> chore(handle): remove update registration

src/core/errors/errors.ts, src/network.ts, src/search.ts
Problem
=======
We don't want any non-implemented methods anymore.
[#178523398](https://www.pivotaltracker.com/story/show/178523398)
Solution
========
Remove them all
=> Remove NotImplementedError

CHANGELOG.md, src/core/contracts/identity.test.ts, src/core/contracts/identity.ts
Add ability to remove delegate from identity contract.
=> feat(identity): add ability to remove delegate

src/core/contracts/subscription.ts
Problem
=======
When `subscription.subscribeToBatchPublications()` is called with a filter fromBlock that includes the contract migrations, this method errors out immediately with an "unknown topic hash" error.
Steps to reproduce:
1. Create a clean chain.
2. Run the contract deploy script.
3. Call `subscribeToBatchPublications(cb, { fromBlock:0, announcmentType: Broadcast })`.
We are using the `PUBLISHER_DECODER.parsseLog()` function to parse the past logs. This breaks for logs that are not publications, and nothing is filtering out the other log events (specifically the contract migration logs).
Solution
========
1. Use the `batchFilter` to filter out non-publication logs.
2. Catch parse errors. These errors should no longer occur, but it's good practice so a corrupted log on-chain …
=> Fix error in batch subscriptions with past logs.

CHANGELOG.md, src/core/contracts/identity.test.ts, src/core/contracts/identity.ts, src/test/utilities.ts
Add ability to resolve all active identities associated
to an address.
=> feat(identity): add ability to get identities

CHANGELOG.md, src/core/contracts/registry.test.ts, src/core/contracts/registry.ts
Add ability to get all registrations associated to
an address.
=> feat(registry): add ability to find by identity

CHANGELOG.md, src/core/contracts/registry.test.ts, src/core/contracts/registry.ts
Add ability to lookup registrations by wallet address.
=> feat(registration): add lookup by wallet address

.github/workflows/main.yml, CHANGELOG.md, package-lock.json, package.json, src/core/contracts/registry.ts
Problem
=======
Minor updates to dependencies and contracts (v1.0.0)
[#179033095](https://www.pivotaltracker.com/story/show/179033095)
Double Checks:
=> Update contracts to v1.0.1 and other minor dependencies

CHANGELOG.md, src/core/contracts/registry.ts, src/core/contracts/subscription.test.ts, src/core/contracts/subscription.ts
Add ability to subscribe to DSNPRegistryUpdate events.
=> feat(registryUpdates): add ability to subscribe 

README.md
We have redeployed the testnet nodes and redeployed the contracts so need to update contract addresses in the README.
Update README with contract addresses
=> update testnet contract addresses

src/core/contracts/registry.test.ts
Problem
=======
Test was having a bit of a race condition sometimes.
Solution
========
Adding in some more mining to try to stop it from being flaky.
=> Correct flaky test

CHANGELOG.md, README.md
Added better config documentation and examples to the Readme
=> Contract Config Documentation

CHANGELOG.md, package-lock.json, package.json
Problem
=======
https://www.pivotaltracker.com/n/projects/2436354/stories/180047688
Security update to tmpl dependency
- Updated tmpl to 1.0.5 as devDependency
=> Upgraded tmpl to 1.0.5 as devDependency
